USE [master]
GO
/****** Object:  Database [InventoryDb]    Script Date: 3/20/2022 10:16:01 AM ******/
CREATE DATABASE [InventoryDb]
GO
ALTER DATABASE [InventoryDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InventoryDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [InventoryDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [InventoryDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [InventoryDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [InventoryDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [InventoryDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [InventoryDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [InventoryDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [InventoryDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [InventoryDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [InventoryDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [InventoryDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [InventoryDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [InventoryDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [InventoryDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [InventoryDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [InventoryDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [InventoryDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [InventoryDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [InventoryDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [InventoryDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [InventoryDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [InventoryDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [InventoryDb] SET RECOVERY FULL 
GO
ALTER DATABASE [InventoryDb] SET  MULTI_USER 
GO
ALTER DATABASE [InventoryDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [InventoryDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [InventoryDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [InventoryDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [InventoryDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [InventoryDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'InventoryDb', N'ON'
GO
ALTER DATABASE [InventoryDb] SET QUERY_STORE = OFF
GO
USE [InventoryDb]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 3/20/2022 10:16:01 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 3/20/2022 10:16:01 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[Barcode_Value] [nvarchar](max) NULL,
	[Description] [nvarchar](200) NOT NULL,
	[Weight_Value] [float] NULL,
	[Status] [int] NOT NULL,
	[Category_Name] [nvarchar](max) NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [InventoryDb] SET  READ_WRITE 
GO
